### ISSUE TITLE
upgrade to the latest tailwind version

### ISSUE THREAD

**Issue by rbeier** [killgt/tailwindcomponents-site#1]
Hi,
it would be great if you could update tailwind to 0.7.4.

Thanks in advance!

**Comment by agustinprod** [comment]
Hi
i'm open to pull request, but i'll take it if no one sends a pull request in a week or two.

Thanks!

**Comment by agustinprod** [comment]
I think i'll wait to the 1.0 release, it seems to be close to release

**Comment by huphtur** [comment]
Got some components ready to add, need 1.0 please

**Comment by agustinprod** [comment]
Done! I'll try to be update more frequently. I added all v0 colors to the theme to avoid destroying all existing components
